site_controllers:
    resource: "@OutlandishAcadOowpBundle/Controller"
    prefix: /
    type: annotation

default_post:
    path: /{slugs}/
    requirements:
        slugs: "[\w-\/]+"
    defaults:
        _controller: OutlandishAcadOowpBundle:Default:defaultPost