services:
    outlandish_acadoowp.faceted_search.search:
        class: Outlandish\AcadOowpBundle\FacetedSearch\Search
        arguments: [@outlandish_routemaster.query_manager, @outlandish_oowp.post_manager]

    outlandish_acadoowp.acf:
        class: Outlandish\AcadOowpBundle\Command\Acf
        arguments: [@outlandish_oowp.helper.wp]

    kernel.listener.outlandish.notfound:
        class: Outlandish\AcadOowpBundle\EventListener\NotFoundListener
        arguments: [@templating.engine.twig]
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException}