services:
    outlandish_acadoowp.faceted_search.search:
        class: Outlandish\AcadOowpBundle\FacetedSearch\Search
        arguments: [@outlandish_routemaster.query_manager, @outlandish_oowp.post_manager]