services:
    outlandish_acadoowp.acf:
        class: Outlandish\AcadOowpBundle\Command\Acf
        arguments: [@outlandish_oowp.helper.wp]

    kernel.listener.outlandish.notfound:
        class: Outlandish\AcadOowpBundle\EventListener\NotFoundListener
        arguments: [@templating.engine.twig]
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException}