services:
    outlandish_acadoowp.search:
        class: Outlandish\AcadOowpBundle\FacetedSearch\Search
        arguments: [@outlandish_routemaster.query_manager, @outlandish_oowp.post_manager]

    outlandish.twig.layout_extension:
        class: Outlandish\AcadOowpBundle\Twig\LayoutExtension
        tags:
            - { name: twig.extension }